### ISSUE TITLE
Build 2579 Stop flight auto start a new

### ISSUE THREAD

**Issue by leachim1** [fhorinek/SkyDrop#186]
Turn on Skydrop --> auto take off --> ater a long flight (2-3h) press long on flighttime --> ends actual flight and directly starts a new one. Should just stop the flight.

**Comment by fhorinek** [comment]
fixed with #185

**Comment by leachim1** [comment]
Still not fixed, if i disable Auto Land and manually click on flighttime to stop recording. It directly starts a new flight. Press it again and it works! But then i have everytime the long real flight and another onbe with 3 sec...
