### ISSUE TITLE
Auto launch

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#291]
Hi,

With the latest version I find that when setting the correct altitude, the skydrop then detects a launch.

Regards

**Comment by colignym** [comment]
This is still a issue,  plus we had more than one shut down in mid flight.  What happened to Skydrop resolving issues quickly?

**Comment by fhorinek** [comment]
Hi colignym,
the time is short and the skydrop is unfortunately not our only project. We are working on the solution.
I think that this should fix the problem. I will release the official fw soon.
[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/1102635/SKYDROP.FW.zip)

**Comment by caiacoa** [comment]
This issue is NOT solved yet (tried with version 3821)!!!

Now the vario stops beeping with "landed" in the middle of the flight. Serveral times. This is a show stopper!
As always vario switches off when you have to fight hard for every single meter on a ridge with turbulent air. Then you need to press again the power button, blow into it ... and loose another valuable meters. And this is really dangerous because as always ypou need to focused on your glider...
And the vario track logs are useless since you cannot combine 2...3...4 tracklogs to a single one of a single flight .....

Please fix it. 
If you want I can turn on Debug logs and send you.

Why not implement a logic which checks for changes in height and speed for let's say 10 seconds to detect a landing/takeoff? 
Best regards. And thanks for your effort. This is not a rant - only a whish to get this bug fixed soon. 
(I love my skydrop. It's much better compared to my old Braeuninger. But ....)

**Comment by fhorinek** [comment]
@caiacoa This problem is unrelated to this issue.

In default settings auto-start will occurs when you change your altitude by +/- 6 meters in 60 seconds. For autol-and you need to stay in range +/-1m in 60 seconds.

You can change the behavior in Settings->Logger->Auto start/land:
You can disable auto-landing by setting zero (disabled) in Land threshold.
Or you can change timeout to higher value for the detection.
The flight will end when you turn off the device.

Anyway the device will detect another take off after landing, there is no need to restart the device.
You can also use the Flight Time (FTime) wigdet to start/stop the flight

**Comment by caiacoa** [comment]
@fhorinek: Will check it out at an after work H&F in an hour ,-)

**Comment by fhorinek** [comment]
Glad to help

**Comment by AmyKosinova** [comment]
Auto start/land works just fine in build 4520 - tested several times on my own, I suggest to close this issue.
